-- =====================================================================
-- PRAGYA YOGA VERSE — DAY 5 MIGRATION
-- Adds beginner_tips + slug to Asanas, populates AI-generated content
-- for beginner_tips and common_mistakes across all 40 asanas.
-- Precautions table is reused as-is for Safety Notes (no new column).
-- =====================================================================

BEGIN;

-- STEP 1: Add new columns
ALTER TABLE Asanas ADD COLUMN beginner_tips TEXT;
ALTER TABLE Asanas ADD COLUMN slug VARCHAR(60);

-- STEP 2: Populate slug for all 40 asanas (short style, matches existing
-- frontend routes e.g. /asana/tree)
UPDATE Asanas SET slug = 'mountain' WHERE asana_id = 'AS001';
UPDATE Asanas SET slug = 'easy' WHERE asana_id = 'AS002';
UPDATE Asanas SET slug = 'thunderbolt' WHERE asana_id = 'AS003';
UPDATE Asanas SET slug = 'auspicious' WHERE asana_id = 'AS004';
UPDATE Asanas SET slug = 'accomplished' WHERE asana_id = 'AS005';
UPDATE Asanas SET slug = 'staff' WHERE asana_id = 'AS006';
UPDATE Asanas SET slug = 'standing-forward-bend' WHERE asana_id = 'AS007';
UPDATE Asanas SET slug = 'half-standing-forward-bend' WHERE asana_id = 'AS008';
UPDATE Asanas SET slug = 'standing-big-toe' WHERE asana_id = 'AS009';
UPDATE Asanas SET slug = 'hand-under-foot' WHERE asana_id = 'AS010';
UPDATE Asanas SET slug = 'garland' WHERE asana_id = 'AS011';
UPDATE Asanas SET slug = 'goddess' WHERE asana_id = 'AS012';
UPDATE Asanas SET slug = 'chair' WHERE asana_id = 'AS013';
UPDATE Asanas SET slug = 'revolved-chair' WHERE asana_id = 'AS014';
UPDATE Asanas SET slug = 'low-lunge' WHERE asana_id = 'AS015';
UPDATE Asanas SET slug = 'warrior-i' WHERE asana_id = 'AS016';
UPDATE Asanas SET slug = 'warrior-ii' WHERE asana_id = 'AS017';
UPDATE Asanas SET slug = 'warrior-iii' WHERE asana_id = 'AS018';
UPDATE Asanas SET slug = 'triangle' WHERE asana_id = 'AS019';
UPDATE Asanas SET slug = 'revolved-triangle' WHERE asana_id = 'AS020';
UPDATE Asanas SET slug = 'extended-side-angle' WHERE asana_id = 'AS021';
UPDATE Asanas SET slug = 'revolved-side-angle' WHERE asana_id = 'AS022';
UPDATE Asanas SET slug = 'half-moon' WHERE asana_id = 'AS023';
UPDATE Asanas SET slug = 'revolved-half-moon' WHERE asana_id = 'AS024';
UPDATE Asanas SET slug = 'wide-legged-forward-bend' WHERE asana_id = 'AS025';
UPDATE Asanas SET slug = 'intense-side-stretch' WHERE asana_id = 'AS026';
UPDATE Asanas SET slug = 'revolved-hand-to-big-toe' WHERE asana_id = 'AS027';
UPDATE Asanas SET slug = 'dancer' WHERE asana_id = 'AS028';
UPDATE Asanas SET slug = 'eagle' WHERE asana_id = 'AS029';
UPDATE Asanas SET slug = 'palm-tree' WHERE asana_id = 'AS030';
UPDATE Asanas SET slug = 'tree' WHERE asana_id = 'AS031';
UPDATE Asanas SET slug = 'gate' WHERE asana_id = 'AS032';
UPDATE Asanas SET slug = 'bound-angle' WHERE asana_id = 'AS033';
UPDATE Asanas SET slug = 'wide-angle-seated-forward-bend' WHERE asana_id = 'AS034';
UPDATE Asanas SET slug = 'fire-log' WHERE asana_id = 'AS035';
UPDATE Asanas SET slug = 'head-to-knee-forward-bend' WHERE asana_id = 'AS036';
UPDATE Asanas SET slug = 'revolved-head-to-knee' WHERE asana_id = 'AS037';
UPDATE Asanas SET slug = 'three-limbed-forward-bend' WHERE asana_id = 'AS038';
UPDATE Asanas SET slug = 'heron' WHERE asana_id = 'AS039';
UPDATE Asanas SET slug = 'seated-forward-bend' WHERE asana_id = 'AS040';

-- STEP 3: Enforce uniqueness + NOT NULL now that all rows are populated
ALTER TABLE Asanas ALTER COLUMN slug SET NOT NULL;
ALTER TABLE Asanas ADD CONSTRAINT uq_asanas_slug UNIQUE (slug);
CREATE INDEX idx_asanas_slug ON Asanas (slug);

-- STEP 4: Populate beginner_tips (new) and common_mistakes (existing,
-- previously NULL) with reviewed AI-generated content
UPDATE Asanas SET beginner_tips = 'Stand in front of a mirror to check that your ears, shoulders, and hips are stacked in one line. Spread your toes wide and press evenly through all four corners of each foot. Keep your knees soft rather than locked to avoid strain.', common_mistakes = 'Locking the knees, which cuts off circulation and strains the joints. Letting the shoulders round forward instead of stacking over the hips. Gripping the toes or clenching the jaw instead of staying relaxed.' WHERE asana_id = 'AS001';
UPDATE Asanas SET beginner_tips = 'Sit on the edge of a folded blanket if your hips feel lower than your knees. Alternate which shin crosses in front each time you practice. Rest your hands lightly on your knees rather than pressing down.', common_mistakes = 'Slouching the lower back because the hips are tighter than the seat height allows. Always crossing the same leg in front, creating imbalance over time. Holding tension in the shoulders instead of letting them soften.' WHERE asana_id = 'AS002';
UPDATE Asanas SET beginner_tips = 'Place a folded blanket behind the knees if you feel pressure there. Keep the tops of the feet flat and toes pointing straight back. Start with shorter holds and build up duration gradually.', common_mistakes = 'Letting the knees splay outward instead of staying hip-width apart. Sitting with the toes turned inward, straining the ankles. Rounding the spine instead of lengthening it from the tailbone.' WHERE asana_id = 'AS003';
UPDATE Asanas SET beginner_tips = 'Tuck both feet snugly between the thigh and calf of the opposite leg. Sit on a cushion if your hips are tight to keep the spine upright. Keep the knees as close to the floor as is comfortable without forcing them.', common_mistakes = 'Forcing the knees down when the hips aren''t ready, straining the joints. Letting the spine slump instead of staying tall. Placing the feet loosely so they slip out during the hold.' WHERE asana_id = 'AS004';
UPDATE Asanas SET beginner_tips = 'Only attempt this pose once Easy Pose and Auspicious Pose feel comfortable, since it needs more hip flexibility. Sit on a blanket to tilt the pelvis forward slightly. Stack the heels one directly above the other rather than side by side.', common_mistakes = 'Forcing the heel stack before the hips are open enough, which strains the knees. Letting the pelvis tilt backward, rounding the lower back. Gripping the shoulders up toward the ears during longer holds.' WHERE asana_id = 'AS005';
UPDATE Asanas SET beginner_tips = 'Sit on a folded blanket if your hamstrings are tight and your back rounds. Press the palms into the floor beside the hips to help lift the spine tall. Flex the feet firmly so the heels reach away from the body.', common_mistakes = 'Rounding the lower back instead of sitting up tall from the pelvis. Letting the shoulders creep up toward the ears. Allowing the knees to bend or the feet to sickle inward.' WHERE asana_id = 'AS006';
UPDATE Asanas SET beginner_tips = 'Bend the knees generously if your hamstrings are tight, rather than forcing the legs straight. Let the head and neck hang heavy instead of tensing them. Rise up slowly with a flat back to avoid dizziness.', common_mistakes = 'Locking the knees while forcing a straight-leg fold, which strains the hamstrings and lower back. Rounding aggressively from the lower back instead of hinging at the hips. Standing up too quickly and feeling lightheaded.' WHERE asana_id = 'AS007';
UPDATE Asanas SET beginner_tips = 'Rest your fingertips on blocks if they don''t comfortably reach the floor. Draw the chest forward to lengthen the spine rather than rounding it. Keep a slight bend in the knees for support.', common_mistakes = 'Rounding the back instead of keeping it flat and extended. Placing the hands too far forward, collapsing the shoulders. Hyperextending the knees to reach the floor.' WHERE asana_id = 'AS008';
UPDATE Asanas SET beginner_tips = 'Loop a strap around the big toe if your hands can''t reach it comfortably. Keep a micro-bend in the standing leg''s knee rather than locking it. Build the fold gradually over several breaths instead of forcing it.', common_mistakes = 'Rounding the upper back sharply to force the hands to the toes. Locking out the standing knee, which strains the joint. Rushing into the full fold before the hamstrings are warmed up.' WHERE asana_id = 'AS009';
UPDATE Asanas SET beginner_tips = 'Slide only the fingers or toes under the feet at first, not the whole palm. Keep a soft bend in the knees to protect the lower back. Breathe steadily instead of holding your breath while folding.', common_mistakes = 'Straightening the knees forcefully to get the palms fully under the feet. Rounding the spine excessively instead of hinging from the hips. Holding the breath during the deep fold.' WHERE asana_id = 'AS010';
UPDATE Asanas SET beginner_tips = 'Place a rolled blanket under the heels if they lift off the floor. Keep the feet turned out slightly to make space for the hips to sink. Press the elbows gently against the inner knees to open the hips.', common_mistakes = 'Letting the heels lift and the weight shift onto the toes. Rounding the upper back instead of keeping the chest lifted. Forcing the knees wide before the hips are warmed up.' WHERE asana_id = 'AS011';
UPDATE Asanas SET beginner_tips = 'Turn the toes out at roughly 45 degrees so the knees can track over them. Keep the tailbone tucking slightly under rather than the low back overarching. Rest the hands on the hips if holding them at chest height feels tiring.', common_mistakes = 'Letting the knees collapse inward past the toes, straining the joints. Overarching the lower back instead of engaging the core. Not sinking low enough for the thighs to feel the work.' WHERE asana_id = 'AS012';
UPDATE Asanas SET beginner_tips = 'Keep the weight in the heels rather than letting it shift onto the toes. Sit the hips back as if lowering onto a chair rather than bending only the knees. Reach the arms forward or up only as high as the shoulders allow without shrugging.', common_mistakes = 'Letting the knees drift forward past the toes. Shrugging the shoulders up toward the ears. Rounding the lower back instead of keeping the spine long.' WHERE asana_id = 'AS013';
UPDATE Asanas SET beginner_tips = 'Establish a stable Chair Pose base before adding the twist. Hook the opposite elbow outside the knee rather than forcing depth in the twist. Keep both knees stacked evenly instead of letting one dip lower.', common_mistakes = 'Twisting mainly from the shoulders instead of rotating through the mid-back. Letting one knee shoot forward while twisting. Losing the squat depth entirely to chase more rotation.' WHERE asana_id = 'AS014';
UPDATE Asanas SET beginner_tips = 'Pad the back knee with a folded blanket for comfort. Stack the front knee directly over the front ankle, not past the toes. Untuck the back toes and rest the top of the foot down for a gentler hip stretch.', common_mistakes = 'Letting the front knee travel past the front ankle, straining the joint. Sinking the hips without engaging the core, which arches the lower back. Placing the back knee directly on a hard floor without padding.' WHERE asana_id = 'AS015';
UPDATE Asanas SET beginner_tips = 'Shorten your stance if your back heel won''t stay grounded. Square the hips toward the front of the mat rather than letting the back hip open sideways. Keep the front knee tracking over the ankle, not caving inward.', common_mistakes = 'Letting the back heel lift off the floor instead of staying rooted. Allowing the front knee to collapse inward past the toes. Leaving the hips open to the side instead of squaring them forward.' WHERE asana_id = 'AS016';
UPDATE Asanas SET beginner_tips = 'Keep the front knee tracking directly over the ankle, not sickling inward. Stack the shoulders over the hips rather than leaning over the front leg. Gaze softly over the front fingertips without straining the neck.', common_mistakes = 'Leaning the torso forward over the front thigh instead of staying upright. Letting the front knee drift inward past the toes. Tensing the shoulders up instead of keeping the arms relaxed and extended.' WHERE asana_id = 'AS017';
UPDATE Asanas SET beginner_tips = 'Practice near a wall for the extended hand or lifted foot to tap for balance. Keep a slight bend in the standing knee rather than locking it. Focus your gaze on one fixed point on the floor to steady the balance.', common_mistakes = 'Locking the standing knee, which destabilizes the balance. Letting the hips tilt open instead of staying level and square. Rounding the back instead of keeping the torso and lifted leg in one long line.' WHERE asana_id = 'AS018';
UPDATE Asanas SET beginner_tips = 'Rest the lower hand on a block or your shin instead of forcing it to the floor. Keep a micro-bend in the front knee to protect the joint. Stack the shoulders vertically instead of letting the torso collapse forward.', common_mistakes = 'Locking the front knee completely, which strains the joint. Collapsing the torso toward the front leg instead of extending the crown of the head forward first. Letting the top shoulder roll forward instead of stacking over the bottom one.' WHERE asana_id = 'AS019';
UPDATE Asanas SET beginner_tips = 'Use a block under the lower hand until your hamstrings and balance allow reaching the floor. Square the hips toward the front of the mat before adding the twist. Keep the back heel grounded and pressing down throughout.', common_mistakes = 'Rotating mainly from the shoulder instead of the spine, which limits the twist and strains the neck. Letting the hips open to the side instead of staying squared. Rounding the back instead of keeping it long during the fold.' WHERE asana_id = 'AS020';
UPDATE Asanas SET beginner_tips = 'Rest the lower forearm on the front thigh instead of reaching the hand to the floor at first. Keep the front knee tracking directly over the ankle. Extend through the top arm and side body to avoid collapsing into the bent knee.', common_mistakes = 'Letting the front knee collapse inward past the toes. Dumping body weight into the front thigh instead of engaging the outer leg. Collapsing the chest downward instead of opening it toward the ceiling.' WHERE asana_id = 'AS021';
UPDATE Asanas SET beginner_tips = 'Master Extended Side Angle and basic twists before attempting this combined pose. Use a block under the lower hand to keep the twist stable. Keep the back heel grounded rather than letting it lift as you rotate.', common_mistakes = 'Letting the back heel lift, which destabilizes the whole pose. Twisting from the neck and shoulders instead of the mid-back. Allowing the front knee to cave inward under the added rotation.' WHERE asana_id = 'AS022';
UPDATE Asanas SET beginner_tips = 'Practice against a wall behind your back for extra balance support. Keep a small bend in the standing leg rather than locking the knee. Stack the hips vertically instead of letting the top hip roll open too far.', common_mistakes = 'Locking the standing knee, which makes the balance shakier. Letting the top hip open too far, twisting the pelvis out of alignment. Looking down at the floor instead of finding a steady gaze point to help balance.' WHERE asana_id = 'AS023';
UPDATE Asanas SET beginner_tips = 'Build a stable Half Moon Pose first, then add the twist gradually. Rest the lower hand on a block to keep the base steady. Keep the lifted leg active and reaching back rather than letting it drop.', common_mistakes = 'Rushing into the twist before the standing balance is stable. Letting the lifted leg drop lower as attention shifts to the rotation. Rounding the spine instead of rotating it evenly.' WHERE asana_id = 'AS024';
UPDATE Asanas SET beginner_tips = 'Place your hands on blocks if they don''t reach the floor comfortably. Keep a soft bend in the knees rather than locking them. Walk the feet only as wide as keeps the toes pointing forward.', common_mistakes = 'Locking the knees while forcing depth in the fold. Turning the feet in different directions instead of keeping them parallel. Rounding the upper back sharply instead of hinging from the hips.' WHERE asana_id = 'AS025';
UPDATE Asanas SET beginner_tips = 'Shorten your stance so the hips can square forward more easily. Rest the hands on blocks beside the front foot instead of reaching the floor. Keep equal weight in both feet rather than dumping it all into the front leg.', common_mistakes = 'Letting the back heel lift instead of staying grounded and squared. Rounding the spine deeply instead of leading the fold with a long back. Twisting the hips open instead of keeping them square to the front.' WHERE asana_id = 'AS026';
UPDATE Asanas SET beginner_tips = 'Use a strap around the lifted foot instead of forcing the hand to reach it. Keep a soft bend in the standing knee for stability. Master seated twists and standing balances separately before combining them here.', common_mistakes = 'Locking the standing knee, which destabilizes an already advanced balance. Twisting from the shoulders instead of rotating the torso as a whole. Letting the lifted leg drop as focus shifts to the twist.' WHERE asana_id = 'AS027';
UPDATE Asanas SET beginner_tips = 'Use a strap looped around the back foot if your hand can''t reach it yet. Keep a soft bend in the standing leg''s knee. Draw the lifted thigh in line with the hip rather than letting it flare out to the side.', common_mistakes = 'Letting the standing knee lock, which reduces stability. Allowing the lifted leg to splay out sideways instead of staying in line with the hip. Collapsing the chest down instead of lifting it as the leg kicks back.' WHERE asana_id = 'AS028';
UPDATE Asanas SET beginner_tips = 'Just cross the thighs and rest the top foot on the floor if a full double wrap feels unstable at first. Keep a soft bend in the standing leg. Sit the hips back slightly as if lowering into a small chair.', common_mistakes = 'Standing too upright instead of sitting the hips back for stability. Letting the standing knee lock straight. Rounding the upper back instead of keeping the chest lifted while the arms wrap.' WHERE asana_id = 'AS029';
UPDATE Asanas SET beginner_tips = 'Rise onto the toes only as high as feels stable, using a wall for support if needed. Reach up through the fingertips rather than shrugging the shoulders to the ears. Keep the core gently engaged to avoid overarching the back.', common_mistakes = 'Shrugging the shoulders up toward the ears while reaching overhead. Overarching the lower back instead of keeping the ribs drawn in. Wobbling from rising onto the toes too quickly.' WHERE asana_id = 'AS030';
UPDATE Asanas SET beginner_tips = 'Place the lifted foot on the ankle or calf rather than directly on the knee joint. Practice near a wall until your balance feels steady. Fix your gaze on one still point to help stabilize the pose.', common_mistakes = 'Resting the foot directly against the knee, which puts unwanted pressure on the joint. Letting the standing hip jut out to the side instead of staying level. Holding the breath while concentrating on balance.' WHERE asana_id = 'AS031';
UPDATE Asanas SET beginner_tips = 'Pad the kneeling knee with a folded blanket for comfort. Keep the extended leg''s foot flat and toes pointing forward. Reach through both sides of the waist evenly instead of collapsing into the stretch.', common_mistakes = 'Collapsing the ribs down into the side bend instead of lengthening first. Letting the extended foot turn inward, straining the knee. Rotating the torso forward instead of keeping it facing the side.' WHERE asana_id = 'AS032';
UPDATE Asanas SET beginner_tips = 'Sit on a folded blanket to tilt the pelvis forward if your hips are tight. Support the outer thighs with blocks or cushions rather than pressing the knees down. Hold the feet or ankles instead of the toes to avoid rounding forward.', common_mistakes = 'Pressing the knees toward the floor forcefully instead of letting gravity open the hips gradually. Rounding the lower back instead of sitting tall. Bouncing the knees up and down instead of holding steady.' WHERE asana_id = 'AS033';
UPDATE Asanas SET beginner_tips = 'Sit on a folded blanket if the pelvis tips backward with legs wide. Keep the kneecaps and toes pointing straight up rather than rolling inward. Lead the fold with the chest instead of reaching the head down first.', common_mistakes = 'Letting the knees roll inward as the legs open wide. Rounding the back sharply instead of hinging from the hips with a long spine. Forcing the legs wider than the hips can comfortably support.' WHERE asana_id = 'AS034';
UPDATE Asanas SET beginner_tips = 'Only stack the shins if your hips allow the top knee to rest comfortably, otherwise keep a gap and support it with a blanket. Sit on a cushion to keep the spine tall. Keep the top foot flexed to protect the ankle.', common_mistakes = 'Forcing the top knee down onto the shin when the hip isn''t open enough, straining the joint. Letting the top ankle stay unflexed, which stresses the joint under load. Rounding the spine instead of staying upright.' WHERE asana_id = 'AS035';
UPDATE Asanas SET beginner_tips = 'Loop a strap around the extended foot if your hands can''t reach it. Keep a soft bend in the extended knee rather than locking it. Fold from the hips with a long spine rather than rounding the back to get lower.', common_mistakes = 'Locking the extended knee, which strains the joint and hamstring. Rounding the back sharply instead of hinging at the hips. Letting the bent knee lift off the floor instead of relaxing it down.' WHERE asana_id = 'AS036';
UPDATE Asanas SET beginner_tips = 'Master the upright version of this seated side stretch before adding the twist. Rest the lower forearm on the shin or a block rather than forcing it to the floor. Keep the extended leg''s knee soft, not locked.', common_mistakes = 'Locking the extended knee while reaching for the foot. Collapsing the chest down instead of rotating it open toward the ceiling. Rushing into the twist before the side body has lengthened.' WHERE asana_id = 'AS037';
UPDATE Asanas SET beginner_tips = 'Only attempt the folded-leg foot position once your ankles and knees tolerate it comfortably; otherwise keep the leg extended instead. Sit on a blanket to protect the folded ankle. Fold forward slowly, leading with the chest.', common_mistakes = 'Forcing the folded ankle and knee into position when they aren''t ready, risking strain. Rounding the back aggressively instead of hinging from the hips. Leaning unevenly toward the extended leg instead of staying centered.' WHERE asana_id = 'AS038';
UPDATE Asanas SET beginner_tips = 'Use a strap around the lifted foot instead of forcing the hands to hold it directly. Keep the grounded shin''s knee cushioned with a blanket. Lift the leg only as high as keeps the spine long, not rounded.', common_mistakes = 'Rounding the back to force the leg higher instead of keeping the torso upright. Forcing the extended knee straight before the hamstrings allow it. Neglecting to cushion the bottom knee, causing discomfort.' WHERE asana_id = 'AS039';
UPDATE Asanas SET beginner_tips = 'Sit on a folded blanket and bend the knees generously if your hamstrings are tight. Loop a strap around the feet instead of straining to reach them. Lead the fold with the chest rather than the head.', common_mistakes = 'Rounding the back sharply to force the hands to the feet. Locking the knees while forcing a straight-leg fold. Rushing the fold instead of easing in gradually with the breath.' WHERE asana_id = 'AS040';

COMMIT;